language: node_js
cache:
  yarn: true
  directories:
    - node_modules

after_success:
  - yarn run test-coverage
  - yarn run check-coverage
  - yarn run report-coverage

env:
- TESTING=true
- NODE_ENV=testing