language: node_js
cache:
  yarn: true
  directories:
    - node_modules

script:
  - yarn run test-coverage
after_success:
  - yarn run check-coverage
  - yarn run report-coverage

env:
  global:
    - TESTING=true
    - NODE_ENV=testing